### ISSUE TITLE
Server side start with twice request

### ISSUE THREAD

**Issue by giolvani** [l-lin/angular-datatables#102]
I'm using with server side processing and when it initializes, the request to server is duplicated.

``` html
<table datatable dt-options="dtOptions" dt-columns="dtColumns"></table>
```

``` javascript
$scope.dtOptions = DTOptionsBuilder.newOptions()
  .withOption('ajax', { url: String.format('{0}api/System/Message/Get', BASEURL) })
  .withDataProp('data')
  .withOption('serverSide', true)
  .withOption('processing', true)
  .withOption('order', [[0, 'asc'], [1, 'asc']])
  .withBootstrap();

$scope.dtColumns = [
  DTColumnBuilder.newColumn('cdMessage').withTitle('Id').withOption('width', 110),
  DTColumnBuilder.newColumn('cdCulture').withTitle('Culture').withOption('width', 100),
  DTColumnBuilder.newColumn('tpMessage').withTitle('MessageType').withOption('width', 160),
  DTColumnBuilder.newColumn('dsMessage').withTitle('MessageDescription'),
  DTColumnBuilder.newColumn('dsDetails').withTitle('MessageDetails')
];
```

![Firebug request](https://c3jzng.by3301.livefilestore.com/y2mEFBBbLZbfvrjArieK3m1WrvJFi9eYW6-RIsaGPXxeLpJ2WBNxTjJz-EF4LFNXNoVWEvLHv13kqPoY8t1nCTGWDmQVSQPJP1E3JCuXzbt40f_LyiPNCe1ExGtusmjvn3b/firebug.PNG?psid=1)

**Comment by yadongwen** [comment]
Hi, I'm seeing the same issue in v0.4.3.

**Comment by dashawk** [comment]
It is because of the promises.

In the first load of your page, you must set the `tableOptions` and `tableColumns` with an empty promise.

```javascript
vm.tableOptions = $q.defer().promise;
vm.tableColumns = $q.defer().promise;

// After Loading the DOM, add your options
vm.tableOptions = DTOptionsBuilder ... // or $resource().query().$promise;
vm.tableOptions = DTColumnsBuilder ... // or $resource().query().$promise;
```

This is what I noticed, if the DOM is not yet ready, the tableOptions will attempt to call for an ajax request, but since the `<table datatable` is not yet present, it will not do anything, you just be able to see the request first hand, then after the DOM is loaded, then the `datatable` directive will start the tableOptions to call for an ajax request, that is why there are two requests after the page load.
