### ISSUE TITLE
Column with form input and angular FormControls

### ISSUE THREAD

**Issue by javix** [l-lin/angular-datatables#1225]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version: 8.9.1
- angular version: 5.2.9
- angular-cli version: 1.7.4
- jquery version: 3.2.1
- datatables version: 1.1.0.16
- angular-datatables version: 5.0.0
</code></pre>

## Current behavior

I need input fields within the table.
See https://datatables.net/examples/api/form.html

I have a column difinition:
```
[
	{
		data: 'name',
		render: (data, type, row, meta) => {
			return '<input class="news-form-control" formControlName="name">';
		}
	}
]
```

And a formGroup:

```
this.myForm = this.fb.group( {
    name: [ 'my name' ],
} );
```
As a result: I see the input field, but it is not bound to the FormControl.

How can I use the angular directives within the render-callback?
Is it even possible?

**Comment by l-lin** [comment]
Unfortunately, I still don't know how because Angular and DataTables are like living in 2 different worlds and can't really communicate to each other. Maybe an expert of Angular can help on this.

Check the #982 as the issue is quite similar as they also need to bind an Angular function to DataTables.
