### ISSUE TITLE
rowCallback & Serverside Angular does not work together

### ISSUE THREAD

**Issue by kekon01** [l-lin/angular-datatables#1394]
Hello I have been trying to get row click event to work with serve side ajax call. I cannot get the rowCallBack to work what so ever. Does anyone know how to resolve this problem?

I am trying to combine the following two example together. Which I think should be a simple task. But I have been searching for a solution online and cannot seem to find anything on this problem. I have been coming back to this problem for a past week know not finding solutions whats so ever.

Example:
http://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way
http://l-lin.github.io/angular-datatables/#/advanced/row-click-event

```js
  ngOnInit() {
    //other code
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10,
      responsive: true,
      serverSide: true,
      processing: true,
      ajax: (dataTablesParameters: any, callback, settings) => {
        this.http
          .post<DataTablesResponse>(
            'placeholder',
            dataTablesParameters, httpOptions
          ).subscribe(resp => {
            this.filteredData = resp.data;
            callback({
              recordsTotal: resp.recordsTotal,
              recordsFiltered: resp.recordsFiltered,
              data: [],
            });
          });
      },
      columns: [{ data: 'product' }, { data: 'name' }, { data: 'vendor' }],
      rowCallback: (row: Node, data: any[] | Object, index: number) => {
        const self = this;
        // Unbind first in order to avoid any duplicate handler
        // (see https://github.com/l-lin/angular-datatables/issues/87)
        $('td', row).unbind('click');
        $('td', row).bind('click', () => {
          self.someClickHandler(data);
        });
        return row;
      }
    };
  }
```

**Comment by LembarkiMedAmine** [comment]
Hi kekon01,

I hope that i'm not coming late :p, so I encountered the same problem , and after some reserach I found this article : [https://www.gyrocode.com/articles/jquery-datatables-responsive-extension-and-custom-controls/](url) which explain this problem : 

> Cause
This problem occurs because Responsive extension performs rendering after the call to function defined by drawCallback option. Therefore custom control initialization performed in createdRow with initRating() doesn’t see markup produced by renderer of Responsive extension and custom controls appear uninitialized.
This behavior is observed in Responsive extension versions 1.0.x and 2.0.0.

The article expose two alternatives and I choose this one : 

> Alternative solution
This solution will work only with Responsive extension 2.0.0 and up. In this version responsive-display event has been added which is triggered when details for a row have been displayed, updated or hidden.



**Modifications**
I changed the data passed to the someClickHandler method to row, and we can use jQuery Selector to find your data from the <td> element.
`ngOnInit() {
    //other code
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10,
      responsive: true,
      serverSide: true,
      processing: true,
      ajax: (dataTablesParameters: any, callback, settings) => {
        this.http
          .post<DataTablesResponse>(
            'placeholder',
            dataTablesParameters, httpOptions
          ).subscribe(resp => {
            this.filteredData = resp.data;
            callback({
              recordsTotal: resp.recordsTotal,
              recordsFiltered: resp.recordsFiltered,
              data: [],
            });
          });
      },
      columns: [{ data: 'product' }, { data: 'name' }, { data: 'vendor' }],
      createdRow: (row: Node, data: any) => {
        $('td', row).off('click').on('click', () => {
          this.someClickHandler(row);
        });
      }
    };
  $('#YOUR_DATATABLE_ID').on('responsive-display.dt', (e, api, row, showHide, update) => {
      if (showHide) {
        $('td', $(row.node()).next()).off('click').on('click', () => {
          this.someClickHandler(row.node());
        });
      }
    });
  }

// Change the someClickHandler 
someClickHandler(row: Node): void {
    const info = {};
    info.id = $('td', row).get(0).innerText;
    info.firstName = $('td', row).get(1).innerText;
    this.message = info.id + ' - ' + info.firstName;
}`
**PS : YOUR_DATATABLE_ID must be changed to the id on component.html
<table id="YOUR_DATATABLE_ID" datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" class="row-border hover"></table>**

**Comment by orphanedlukas** [comment]
@stale https://jquerys.space/questions/utilizing-jquery-for-event-handling-in-dynamically-created-table-rows-in-a-datatable
