### ISSUE TITLE
Angular+Datatable boostrap 4 support unclear documentation.

### ISSUE THREAD

**Issue by chr1soscl** [l-lin/angular-datatables#1412]
Not really a code issue, I am trying to find comprehensible documentation on how to implement bootstrap 4 styling to Angular+Datatables, I know there is this page:
https://datatables.net/examples/styling/bootstrap4.html
but this link doesn't explain what npm package to install and what files to import in the angular.json configuration. Can someone add this to the documentation please? I love Datatables, I would love to apply some bootstrap to get them look real nice.

**Comment by gladkiy** [comment]
I also didn't find docs for it but I resolved this issue for my project in the following way:
I used this [page](http://l-lin.github.io/angular-datatables/#/getting-started) but instead of installing
`npm install datatables.net-dt --save`
you need to install
`npm install datatables.net-bs4 --save`
And into `angular.json` file I did the following changes:
```
"styles": [
    ...
    "node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css",
    ...
],
"scripts": [
    ...
    "node_modules/jquery/dist/jquery.js",
    "node_modules/datatables.net/js/jquery.dataTables.js",
    "node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js",
    ...
]
```
Don't forget to install bootstrap v4
