### ISSUE TITLE
Angular Datatables determining the number of records coming from server side.

### ISSUE THREAD

**Issue by ipsitam** [l-lin/angular-datatables#169]
I want to hide the table if there are no records coming from backend. how would i know the count of number of records coming up?

**Comment by l-lin** [comment]
You can use the DT API [data()](https://datatables.net/reference/api/data()) to fetch the data returned by the server and check if the length is > 0.

One solution:
```html
<div ng-if="displayTable">
    <table datatable dt-options="dtOptions" dt-columns="dtColumns" class="row-border hover"></table>
</div>
```
*Note:* The `ng-if` is in the `div` that wraps the table because datatable adds other stuffs like the search input, the pagination... By putting it on level above, we ensure that everything from datatables is hidden.
```js
$scope.dtOptions = DTOptionsBuilder.fromSource('data.json')
    .withPaginationType('full_numbers');
$scope.dtColumns = [
    DTColumnBuilder.newColumn('id').withTitle('ID'),
    DTColumnBuilder.newColumn('firstName').withTitle('First name'),
    DTColumnBuilder.newColumn('lastName').withTitle('Last name').notVisible()
];
// You need to initialize to true so that the datatable directive is triggered
$scope.displayTable = true;
$scope.$on('event:dataTableLoaded', function(event, loadedDT) {
    // Add $timeout to be sure that datatable has finished rendering before calling checking the length
    $timeout(function() {
        $scope.displayTable = loadedDT.DataTable.data().length > 0;
    }, 0, false);
});
```

**Comment by ipsitam** [comment]
It did not serve my purpose. The table still shows up incase no data found.

**Comment by l-lin** [comment]
My bad, you need to set the third parameter of `$timeout` to `true` so that the `$apply` is invoked and the `displayTable` will be updated. Moreover it seems you need to add a minimum delay... So it's not really a good solution.

Here another solution using [initComplete](https://datatables.net/reference/option/initComplete) on [plnkr](http://embed.plnkr.co/RrA8rgrHwYwHYPaElYHv/).
