### ISSUE TITLE
after loading Data  from api using ngFor loop the pagination ,sorting and search not works

### ISSUE THREAD

**Issue by Zain-Malik-7** [l-lin/angular-datatables#1700]
![1](https://user-images.githubusercontent.com/116267450/209145099-8b9f31b5-5210-4bb6-b056-922c559fa8b0.png)

**Comment by shanmukhateja** [comment]
Hello,

The usage of `ngFor` and other Angular specific directives are deprecated and I plan on marking them as Deprecated in the next few days.

Please use `data` property inside AJAX callback (instead of setting to empty array) and let Datatables.net library render the table.

If you have an advanced use case, please use `TemplateRef` or Angular Pipes as per our documentation.

**Reference:**
https://l-lin.github.io/angular-datatables/#/advanced/using-pipe

https://l-lin.github.io/angular-datatables/#/advanced/using-template-ref

I am closing this issue now :)
