### ISSUE TITLE
Cannot make your code sample [Using Angular TemplateRef] working

### ISSUE THREAD

**Issue by stherrienaspnet** [l-lin/angular-datatables#1804]
# :beetle: bug report

## :microscope: Minimal Reproduction
Just start StackBlitz and you will see nothing show

**StackBlitz/GitHub Link:**
https://stackblitz.com/edit/stackblitz-starters-ybvdpx?file=src%2Fexample%2Fusing-ng-template-ref.component.ts

**Step-by-step Instructions:**
Just start StackBlitz and you will see nothing show

## :globe_with_meridians: Your Environment

- NodeJS version: 
- Angular version: 18.1.3
- Angular CLI version: 18.1.3
- jQuery version: 3.6.0
- DataTables version: 2.0.8
- angular-datatables version: 18.0.0

## :memo: Additional context

If you could make this StackBlitz working that would be really nice and help others in the future.

**Comment by stherrienaspnet** [comment]
Reproduction is easy just need to run stack blitz :)

**Comment by shanmukhateja** [comment]
Hello,

It turns out, I forgot to add `[dtTrigger]="dtTrigger"` in the table's HTML documentation related code. We are using this snippet for the preview generation but I failed to copy it over to the HTML specific file.
Feel free to append the snippet above  beside `dtOptions`  in your component's HTML code.

## Explanation
When we don't have `dtTrigger` set by the HTML, we initialize the table when the Angular directive is ready. If `dtTrigger` is specified, we hold off the initialization part until the component code triggers it.

## Attachment
[template-re.zip](https://github.com/user-attachments/files/16512428/template-re.zip)

**Comment by stherrienaspnet** [comment]
Thank you very much Surya!

Le mar. 6 août 2024 à 11:29, Surya Teja K ***@***.***> a
écrit :
