### ISSUE TITLE
Cannot make your code sample [Router-link] runnning

### ISSUE THREAD

**Issue by stherrienaspnet** [l-lin/angular-datatables#1805]
# :beetle: bug report

I cannot have your code sample running properly. There is no error but the datatable is not showing,

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:**

https://stackblitz.com/edit/stackblitz-starters-c13cah?file=src%2Fexample%2Frouter-link.component.ts

**Step-by-step Instructions:**

Just run the StackBlitz and you will see

## :8ball: Expected behavior

See the datatable

## :globe_with_meridians: Your Environment

- NodeJS version: 
- Angular version: 18.1.3
- Angular CLI version: 18.1.3
- jQuery version: 3.6.0
- DataTables version: 2.0.8
- angular-datatables version: 18.0.0

**Comment by shanmukhateja** [comment]
Hi,

I would recommend not using `schemas:[NO_ERRORS_SCHEMA],` if at all possible as it can hide genuine errors from Angular.

There are other project setup related issues mostly due to [standalone components](https://angular.io/guide/standalone-components) which is the default starting from v17.

You can find the attached zip file for a working example.

[router-link.zip](https://github.com/user-attachments/files/16512465/router-link.zip)

**Comment by stherrienaspnet** [comment]
Thank you very much Surya!

Le mar. 6 août 2024 à 11:32, Surya Teja K ***@***.***> a
écrit :
