### ISSUE TITLE
[Question]: AJAX call failure handling

### ISSUE THREAD

**Issue by devlanp** [l-lin/angular-datatables#221]
May be a very basic question ! But looking for an answer in the angular-datatables way ! How does it handle the AJAX call failures or how do we get control on the AJAX call failure returning a meaningful message back to the user without any weird POPUP's !

**Comment by l-lin** [comment]
You need to provide the attribute `ajax.error`:
```js
vm.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('ajax', {
        url: 'data.json',
        error: function(xhr, error, thrown) {
            // Do you error handling here
        }
    });
```

**Comment by devlanp** [comment]
What is the default behaviour ? I remember seeing some pop ups when the third party services threw 500 error. Just want to be sure it doesn't resurface after this change aswell.

**Comment by devlanp** [comment]
To be more precise any field (like the 'processing' field) referred earlier which I could use to set in error block of AJAX failure to display the error message back to the user ?

**Comment by l-lin** [comment]
angular-datatables does not really have any error handling.
So it's either DataTables that handles errors, ie throwing some ugly alerts.
Otherwise, everything is in the console.

If you want to customize errors, not only DataTables but Angular and JS exceptions too, one way is to  intercept exceptions with Angular decorator and call some notifications, like [Bootstrap modals](http://angular-ui.github.io/bootstrap/#/modal).

**Comment by devlanp** [comment]
It would have been nice to have a message displayed within the table to display an error message like "processing..." and "loading..." is displayed given the fact that the popups or modals are annoying :-( Anyways, thanks.

**Comment by victorleal** [comment]
Good point here. 

Using the `error`handling function from the Datatables ajax option does not work with the `$scope` of Angular. I can see the `$scope`, change its properties, but they don't reflect on the page (I have some `div` to show messages about the errors).

It seems that the ajax option creates a scope that can change stuff in the Angular controller scope, but these changes **do not reflect** on the page (maybe because the changes are not done by the Controller itself, but by some external entity).

**Comment by OdinTech3** [comment]
victorleal is right about the issue with `$scope` of controller not changing in the DOM. How i solved it was by using ES6 arrow functions for the ajax.error. So it ended up looking something like this

```
vm.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('ajax', {
        url: 'data.json',
        error: (xhr, error, thrown) => {
            // Do you error handling here
        }
    });
```
Using arrow function you can change member variables/properties of the controller which will change it in the scope of the DOM/page.
