### ISSUE TITLE
Bootstrap TableTools Layout Issue

### ISSUE THREAD

**Issue by devlanp** [l-lin/angular-datatables#223]
Observed that the placement of table tool options "breaks" while using with ".withBootstrap()". Attaching screenshots of both. Not sure if it is as expected. I was expecting the layout would remain same.

![with-bootstrap](https://cloud.githubusercontent.com/assets/10979563/6194931/1b08bb2e-b3ef-11e4-800b-ce6825b1f506.jpg)
![without-bottstrap](https://cloud.githubusercontent.com/assets/10979563/6194930/1b06d994-b3ef-11e4-8eb4-86e27a6c1e52.jpg)

**Comment by l-lin** [comment]
By default, the [dom](https://datatables.net/reference/option/dom) used for the DataTable is `lfrtip`. You can see the default options used by angular-datatables in the [source code](https://github.com/l-lin/angular-datatables/blob/v0.4.0/src/angular-datatables.options.js#L5).

With Bootstrap, the default options is `<\'row\'<\'col-xs-6\'l><\'col-xs-6\'f>r>t<\'row\'<\'col-xs-6\'i><\'col-xs-6\'p>>`. You can also check the default options used in the [source code](https://github.com/l-lin/angular-datatables/blob/v0.4.0/src/plugins/bootstrap/angular-datatables.bootstrap.options.js#L45).

The reason I used a different dom is because I just fetch the Bootstrap example from [DataTables](https://datatables.net/examples/styling/bootstrap.html) and did not bother to change it.

**Comment by devlanp** [comment]
Any quick suggestions to fix the alignment in bootstrap would be helpful... Else, never mind... Will spend some time :-)

**Comment by devlanp** [comment]
Found another issue... This time with the header... It doesn't seem to be responsive with bootstrap and scroller in place.. Did I miss anything ?

**Comment by l-lin** [comment]
I don't know, I never test it using so many plugins at the same times...

**Comment by devlanp** [comment]
Ok. Thanks for your support.
