### ISSUE TITLE
Can't acess api for datatables

### ISSUE THREAD

**Issue by rmarinho** [l-lin/angular-datatables#23]
I starting using this framework, but i found out that i can' acess the DataTables api:

```
    $scope.dtOptions = DTOptionsBuilder.fromFnPromise($scope.getData()).withBootstrap()
   .withOption('footerCallback', function (row, data, start, end, display) {
        var api = this.api(), data;
```

the api varable is a empty array

**Comment by vincilbishop** [comment]
See this issue here, this is how you can get to the DataTables API: https://github.com/l-lin/angular-datatables/issues/824 

I will make one note for anyone else that finds themselves here from Google...reference the dtInstance.DataTable without the (), e.g. dtInstance.DataTable.row() will work, contra the datatables.net documentation.
