### ISSUE TITLE
Create multiple controllers when using angular way and ng-repeat

### ISSUE THREAD

**Issue by pzborek** [l-lin/angular-datatables#363]
When using angular way and ng-controller with ng-repeat on same scope it duplicates controller instance after adding new item.
Here is an example: http://plnkr.co/edit/xqBI3bqFm5KFo5QUMUsE?p=preview
Look console output.

**Comment by hjzheng** [comment]
Your repeat-controller and directive ng-repeat in the same html element. The priority of ng-repeat is higher than ng-controller. So first run ng-repeat, then run ng-controller.  
about directive priority you can read this: https://docs.angularjs.org/api/ng/service/$compile#directive-definition-object

**Comment by pzborek** [comment]
I know priority. The same thing without datatables works fine. Problem occurs only for datatable="ng". I need every single list item had own controller, but each adding create new instance so efect is one item has multiple controllers...

**Comment by hjzheng** [comment]
Yes, you are right, I think this is a bug.  @l-lin  please help to fix it.

**Comment by l-lin** [comment]
It does not really duplicate the controller instances.
If you look at this [code](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.renderer.js#L189), you will notice that each time your list is changed, the DOM element of the table is first destroyed, and then recompiled.
That's why on your example, when you click on the button "Add", the controller instances are destroyed and then re-instancied, thus having the messages on the console.

Unfortunately, I don't know any solution to your issue, or any workaround, for the Angular renderer is working this way (can't find any other alternative to make it work the "angular way").

**Comment by pzborek** [comment]
The main problem is that if in these controllers is added watch, then change the list cause multiple calls of watch function.
