### ISSUE TITLE
Externally destroying a DataTable can lead to a memory leak

### ISSUE THREAD

**Issue by DataTables** [l-lin/angular-datatables#377]
I've recently been looking into a memory leak issue for a DataTables user who makes use of your handy library (thanks for providing it!).

What appears to be happening is that the DataTable is being destroyed use the DataTables `destroy()` method, but then the data source that has been powering the DataTable data (from an `ng-repeat`) is updated. That is causing the DataTable to be reinitialised by this library and thus a leak occurs.

I've put an [example together showing the issue](http://datatables.net/dev/angular-memory/leak.html). To reproduce, just start a profile in Chrome and then run the `run()` method in the console.

I've also [put an example together](http://datatables.net/dev/angular-memory/noleak.html) that does not modify the data source after the DataTable has been destroyed and does not exhibit this issue.

As a possible fix, perhaps it would be possible to listen for the `destroy.dt` event from DataTables and when found, stop performing any updates to the DataTable. This would require an external destroy event to be distinguished from an internal one, as I see you use the destroy at lot internally.

**Comment by l-lin** [comment]
I see. Thanks for reporting it :+1:

**Comment by l-lin** [comment]
I think it's resolved with #326.
As I'm quite new with profiling JS codes, can you point out where the leak is in the chrome profiling manager?
Because I can't see the difference between the one with the memory leak and the one without.

Using Chrome timeline, with leak:
![leak](https://cloud.githubusercontent.com/assets/5452304/9577705/ddb8ae50-4fe3-11e5-9fd5-d69751d5a720.png)
Without leak:
![noleak](https://cloud.githubusercontent.com/assets/5452304/9577707/e14b5f40-4fe3-11e5-95dc-07b221820323.png)

Is it the number of listeners?

Thanks!

**Comment by deifos** [comment]
Any updates on this issue?

**Comment by l-lin** [comment]
Unfortunately, as Angular 2 is coming out, I lack the motivation to find the fix for this peculiar bug for the versions 0.X.X of angular-datatables... If some kind soul is willing to fix this... :confounded:

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
