### ISSUE TITLE
Writing Test for Pull Request

### ISSUE THREAD

**Issue by kyleguate** [l-lin/angular-datatables#401]
## Intro
This is a request for feedback on the test that supports the new code I've added to this project. Any feedback on the new code itself is welcome.  Please see https://github.com/kyleguate/angular-datatables - dev branch and read below for the full details. 

## Pull Request Purpose
The purpose of the pull request is to enable the developer to apply any necessary formatting/transformation required to the response of a resolved promise within the 'dtPromiseRenderer'.  This is important if you are consuming an API for which you do not have control over how the returned response is structured.  For example, I consume an API which returns a response envelope similar to this:
```json
 { "HasErrors": "false", "Errors": [], "Data": [] }
```
Looking at the json response above, I need to index into the Data property which then returns the array of data that I need.

## Pull Request Details 
The pull request adds a feature to the 'dtPromiseRenderer' in the 'angular-datatables.renderer.js' file that checks for an optional callback set on renderer.options. This callback is named 'promiseResponseTransformer'.  Inside the `function _startLoading` it invokes the callback **if it was provided**.  Here are the files and the line numbers:

### New Code
https://github.com/kyleguate/angular-datatables/blob/dev/src/angular-datatables.renderer.js
lines 322-325

### Tests
https://github.com/kyleguate/angular-datatables/blob/dev/test/spec/angular-datatables.renderer.promiseResponseTransformer.spec.js

#### Test Results
If you run the new test that I added it fails on line 28. I have determined that the promise's then in 'angular-datatables.renderer.js' on line 321 does not step into the callback.  

How should I change my code/test so that I can write a test that passes?

#### Alternative Approach
The only other approach I can think of is to abstract the new code out into it's own function.  This makes sense if
**a)**  The function could be used in other places (I don't think so), or
**b)**  It makes it easier to test (which it does)

Are there any downsides to this approach?  If it is good, where would I stick the function and how would I test it?

## Other Notes
I elected to use the promise renderer because the documentation showed examples using ngResource, which I use quite a bit in my angular app.

**Comment by l-lin** [comment]
Interesting idea.
Here some points:
* I don't think you need to handle when the promise fails, at least the way you are handling it is not correct. Indeed, if the promise fails, you will not receive data to be displayed in the table. So instead of using `defer.resolve`, you should be using `defer.reject`.
* Can you add an example of using such transformer in the demo?
* On a side note, if your data is `{ "HasErrors": "false", "Errors": [], "Data": [] }`, you don't really need to use a transformer, you just need to provide a `sAjaxDataProp` like this:
```js
vm.dtOptions = DTOptions.fromFnPromise(function() {
    return somePromise;
})
.withDataProp('Data');
```
* In your test, if you want the promise to be resolved, you need to call `$rootScope.$apply()`. Indeed, angular's promises are not the same as Q's ones. They are deeply dependent of angular's digest cycles. By calling `$rootScope.$apply()`, you are calling the next digest, thus resolving your promise.

Hope that helps.

**Comment by kyleguate** [comment]
Thanks for the feedback.

Here are my responses to your points (numbered sequentially)

1)  You are correct.  I added the following snippet to handle the promise rejection
```javascript
function(result) {
                _loadedPromise = null;
                defer.reject(result);
            });
```

If we don't set the `_loadedPromise = null` here we run into an issue where the table no longer can changeData since it thinks the promise is still unfulfilled (at least that is what I understand to be the problem).

2)  I don't think I have a valid use case for having a transformer now when I can use the `sAjaxDataProp` option as you suggested.

3)  See #2

4)  Thanks for the tip!
