### ISSUE TITLE
Searchable columns using server side

### ISSUE THREAD

**Issue by ssuhat** [l-lin/angular-datatables#459]
I'm trying to set search disable on specific column. Im using this angular datatable server side.

https://l-lin.github.io/angular-datatables

usually on jquery i can just:

      columns:[{data:"foo", name:"foo", searchable:false}]
I've tried use:

      $scope.dtOptions = DTOptionsBuilder.newOptions()
            .withOption('ajax', {
                url: apiRoot + 'merchant-list'
            })
            .withDataProp('data')
            .withOption('serverSide', true)
            .withOption('order', [0, 'asc'])

      $scope.dtColumns = [
            DTColumnBuilder.newColumn('name', 'Name'),
            DTColumnBuilder.newColumn('type', 'Type'),
            DTColumnBuilder.newColumn('username', 'Username'),
      ]

      $scope.dtColumnDefs = [
            DTColumnDefBuilder.newColumnDef(0),
            DTColumnDefBuilder.newColumnDef(1).withOption('searchable', false),
            DTColumnDefBuilder.newColumnDef(2).withOption('searchable', false)
        ]
seems to work but, the position of columnDef is not correct. when i put newColumnDef(1) searchable to false, the column not to be search should be the second one, but apparently it disable the first column. When i put 0 it not disable anything.

Is there way to make it disabled search for specific column and order it?

Edit:
I've tried 'orderable',false and notvisible is working on columnDef 0. Looks like only searchable is fail.

Thanks

**Comment by l-lin** [comment]
Try to use only `dtColumns`:
```js
$scope.dtColumns = [
        DTColumnBuilder.newColumn('name', 'Name'),
        DTColumnBuilder.newColumn('type', 'Type').withOption('searchable', false),
        DTColumnBuilder.newColumn('username', 'Username').withOption('searchable', false),
  ];
```

**Comment by ssuhat** [comment]
I've tried that. but still failed. the first column can be search. 

I've tried using non server side its working properly. but when i change to server side its not working.

Thanks

**Comment by l-lin** [comment]
It might be releated to #445. The issue is that the function `withOption` only accepted a `String`.
Try to use the dev version and tell me if you still encounter the issue.

**Comment by bolemeus** [comment]
Because you're using serverside processing, the actual searching also takes place serverside.
You need to make sure that your backend only returns the filtered data after a search.

Because orderable and visible are clientside options, datatables knows what to do with them when serverside processing is enabled. Thesame cannot be said for searching.

For example if you use the following query to fetch data for your datatables:

```
SELECT u.name, u.type, u.username FROM USERS u;
```

Then make sure you include a where-clause when datatables fetches a new resultset from your backend after a search has been applied.

```
SELECT u.name, u.type, u.username FROM USERS u
WHERE u.name LIKE '%John Doe%';
```

**Comment by ssuhat** [comment]
@bolemeus Hi, on jquery datatable i don't need to specify anything on server side. I just need to put searchable to false and datatable do it for me.

**Comment by l-lin** [comment]
Can you post what is sent to the server when you type in the search input?
You should have a `columns[1][searchable]:false` in the parameters of the request.

As @bolemeus said, it's your server that will do the job of checking which column must be searched since you set the option `serverSide` to `true`.
