### ISSUE TITLE
Rendering next page issue with iCheck control.

### ISSUE THREAD

**Issue by zoell** [l-lin/angular-datatables#519]
Hi,

I am trying to do some experiment with an iCheck (http://fronteed.com/iCheck/) control to select rows and just noticed that when the next page is rendered the whole container div will be clickable and always the last row will be selected. This is happening in Chrome (v46), but not in FF (v42)

Here is what I have so far:
https://jsfiddle.net/mwkzzgfw/30/

If you try to select the rows in the first page, all fine. But if you go to the next page, you won't be able to select any row, the whole iCheck control somehow takes over the whole container div and if you click, the last one will be selected.

Any help would be appreciated.
zoell

**Comment by zoell** [comment]
Is there any thoughts on this?

**Comment by JosephGarrone** [comment]
This issue is occurring because the `icheckbox_flat-blue` div that holds the input is losing its `position: relative` inline styling when you change page, causing the `ins.iCheck-helper` to expand to 100% of the first parent with `position: relative`.

You can see a fix here - https://jsfiddle.net/JosephGarrone/mwkzzgfw/31/

Note: This does not seem like an issue with `angular-datatables`
