### ISSUE TITLE
Problem with sortable function

### ISSUE THREAD

**Issue by eduardocintra** [l-lin/angular-datatables#521]
Hello, guys.

I have a doubt and i don't know if it is a bug.

I'm using angular-datatables with laravel framework through of Laravel Datatables (http://datatables.yajrabox.com/s).

The problem is in the sortable function, i have a table with a column "Select all". I'm disabling sortable with "notSortable()" function.

My table has the following columns:

SELECT ALL | ID | NAME

When i click to sort the id column, the parameter that is sent to my back-end is:
```
order[0][column]:1
order[0][dir]:desc
```
But if I disabled the first column "select all" should not be "order[0][column]:0"?

My problem is that in back-end I don't make reference to the column "select all", as you can see:

```
$escolaridade = Escolaridade::select(array('id','name'));
```
I know that i can resolve this with:
```
$escolaridade = Escolaridade::select(array(1 => 'id',2 => 'name'));
```
but im using the same table in different places, one has the column "select all" and the other has not.

Is there another solution?

**Comment by l-lin** [comment]
Not sure if I really understand your issue (I'm guessing you are using the server side processing), but even if you set your first column as not sortable, the request sent to your server will still be `order[0][column]:1` because DataTables does not know that your first column is not "present" in your server.

So you will need to take into account this index in your server.
