### ISSUE TITLE
Show loading in <tbody> instead of whole table

### ISSUE THREAD

**Issue by ivastag** [l-lin/angular-datatables#522]
Is it possible to make the loading work functionally the same as Datatables?

If you are waiting for promise or response, loading is shown as first rowspan in table.

**Comment by l-lin** [comment]
Unfortunately, as long as DataTables does not have any option for promises, it's not really possible to insert the loading message inside the table as it's not rendered yet.

Unless angular-datatables draws it, then displays the loading and finally destroys the table so that DataTables renders the table again with the data... But as you can see, it's quite tedious and prone for difficult issues (eg the table will certainly "blink" as it's rerendered, or I will need to support theme like bootstrap, and so on...).
