### ISSUE TITLE
How can I integrate YADCF

### ISSUE THREAD

**Issue by vysak** [l-lin/angular-datatables#537]
What is the way to integrate YADCF with this project. I am not able to find any event corresponding to  the table render finished or table initialization. What is the way to do that

**Comment by l-lin** [comment]
See this [comment](https://github.com/l-lin/angular-datatables/issues/358#issuecomment-116163993).

**Comment by McGiogen** [comment]
This works.

## angular-datatables.yadcf.js

```javascript
angular.module('datatables.yadcf', ['datatables'])
    .config(dtYadcfConfig)
    .run(initYadcfPlugin);

/* @ngInject */
function dtYadcfConfig($provide) {
    $provide.decorator('DTOptionsBuilder', dtOptionsBuilderDecorator);

    /* @ngInject */
    function dtOptionsBuilderDecorator($delegate) {
        var newOptions = $delegate.newOptions;
        var fromSource = $delegate.fromSource;
        var fromFnPromise = $delegate.fromFnPromise;

        $delegate.newOptions = function() {
            return _decorateOptions(newOptions);
        };
        $delegate.fromSource = function(ajax) {
            return _decorateOptions(fromSource, ajax);
        };
        $delegate.fromFnPromise = function(fnPromise) {
            return _decorateOptions(fromFnPromise, fnPromise);
        };

        return $delegate;

        function _decorateOptions(fn, params) {
            var options = fn(params);
            options.withYadcf = withYadcf;
            return options;

            /**
             * Add column filter support
             * @param yadcfOptions the plugins options
             * @returns {DTOptions} the options
             */
            function withYadcf(yadcfOptions) {
                options.hasYadcf = true;
                if (yadcfOptions) {
                    options.yadcfOptions = yadcfOptions;
                }
                return options;
            }
        }
    }
}

/* @ngInject */
function initYadcfPlugin(DTRendererService) {
    var yadcfPlugin = {
        postRender: preRender,
    };
    DTRendererService.registerPlugin(yadcfPlugin);

    function preRender(options, result) {
        if (options && options.hasYadcf) {
            yadcf.init(result.DataTable, options.yadcfOptions)
        }
    }
}
```

Use it like following:

```javascript
var dtOptions = DTOptionsBuilder.newOptions()
    .withYadcf([{
        column_number: 0,
        filter_type: 'text',
        filter_reset_button_text: false,
    }]);
```

This uses the **D**ataTable API.

**Comment by wpxgit** [comment]
@McGiogen 
I've tried your solution - but no luck. The Filter Elements are not showing up:
https://embed.plnkr.co/aNOFasiy3pJClpbD5KKq/

Any idea what i am doing wrong?

**Comment by McGiogen** [comment]
I'm sorry but I don't know... With debug you can see that yadcf.init() is correctly called so the problem is not in my yadcf plugin, there should be a problem with something else.
I can suggest you to try to run a really simple example (with jquery datatables + jquery yadcf) then you can add angular-datatables (with jquery yadcf - use attribute dtInstance to have DataTables object), finally add my plugin.

**Comment by Xaldin90** [comment]
@wpxgit 
I came across this solution and it didn't work for me either. But I figured out what the problem was:

`if ($(instance.selector).length === 1) {
			setOptions(instance.selector, options_arg, params);
			initAndBindTable(instance, instance.selector, 0, oTable);
		} else {
			for (i; i < $(instance.selector).length; i++) {
				$.fn.dataTableExt.iApiIndex = i;
				selector = instance.selector + ":eq(" + i + ")";
				setOptions(instance.selector, options_arg, params);
				initAndBindTable(instance, selector, i, oTable);
			}
			$.fn.dataTableExt.iApiIndex = 0;
		}`

That's a piece of code from the yadcf init function. The problem ist, that "instance.selector" is always an empty string. So the if statement falls back to else part. But unfortunately it doesn't work either, cause length is 0. Therefore no filter will ever be visible. A dirty workaround will be to change the initYadcfPlugin function like this:

`function initYadcfPlugin(DTRendererService) {
    var yadcfPlugin = {
        postRender: postRender
    };
    DTRendererService.registerPlugin(yadcfPlugin);

    function postRender(options, result) {
        result.DataTable.settings()[0].oInstance.selector = 'table#' + result.DataTable.context[0].sTableId;
        if (options && options.hasYadcf) {
            yadcf.init(result.DataTable, options.yadcfOptions);
        }
    }
}`

But this will only work, if you have only one table at the same page.
