### ISSUE TITLE
The Data is printed in console, Assigned to $scope but NOT printing in HTML

### ISSUE THREAD

**Issue by mwgi2005** [l-lin/angular-datatables#581]
Problem:
Let me try to explain what I want in one or two lines, In Demo 1 where I've used Angular Datatables when I click on Edit button the data DOES NOT appear in Edit form, whereas in Demo 2 I haven't used any datatables but the data is clearly appearing in edit form, I want the data to appear in Demo1 using Datatables.

Demo1: http://plnkr.co/edit/EXXbkPUHfxcZ3blzvMaz?p=preview
Demo2: http://plnkr.co/edit/QYZzmJNwWTQaIgvUkRzQ?p=preview

**Comment by l-lin** [comment]
In your first demo, you have defined twice the `colony_Controller` in your HTML.
When you click on the edit button, you assign the variable in the nested `colony_Controller`, whereas your form is in your first controller.
See the corrected [plnkr](http://plnkr.co/edit/tt1aiJ7wmFccWbhEJeUO?p=preview).

On a side note, you don't have to use the controller as in order to use angular-datatables. I used in the examples in preparation for Angular 2 (the Angular team recommended using the Controller AS syntax so that the migration will be smoother).
