### ISSUE TITLE
angular-datatables.css is missing

### ISSUE THREAD

**Issue by MadddyByakodi** [l-lin/angular-datatables#634]
HI 
In index.html there is reference to style sheet 
rel="stylesheet" href="dist/css/angular-datatables.css"
But the files is missing please can provide the file

**Comment by l-lin** [comment]
:+1:

**Comment by MadddyByakodi** [comment]
:+1:

**Comment by angus-strut** [comment]
Is there a timeline for when this fix will be released to Bower?

**Comment by aishuiyer2001** [comment]
hi, can you tell me how this was fixed? I can't find 'angular-datatables.css'. I just did a bower install.
This is what gets added   
    <link rel="stylesheet" href="bower_components/datatables/media/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="bower_components/angular-datatables/dist/plugins/bootstrap/datatables.bootstrap.css" />

**Comment by drayvock** [comment]
@aishuiyer2001 The fix is in milestone 0.5.4 and hasn't been merged to master (and is thus not available via Bower yet). I'm currently getting around this issue by manually downloading the CSS file here: https://github.com/l-lin/angular-datatables/tree/dev/dist/css

Alternatively, you could just wait until the fix is merged to master and the npm package is updated. =)
