### ISSUE TITLE
Missing implementation of reloadData

### ISSUE THREAD

**Issue by jmtt89** [l-lin/angular-datatables#759]
I'm trying to use the method for ReloadData as the documentation says (https://l-lin.github.io/angular-datatables/#/dataReloadWithAjax) but don't work,

i check with the Chrome Inspector and try to debug the trace, i found this function:

File: angular-datatables.js
Line: 452

```
function reloadData(callback, resetPaging) {
    /*jshint validthis:true */
    this._renderer.reloadData(callback, resetPaging);
}
```

And the method reloadData
File: angular-datatables.js
Line: 821

```
function reloadData() {
    // Do nothing
}

```

So i think maybe the way to reload data is different now and the docs are outdate or some is broken in generation of angular-datatables.js in dist directory

if you can verify this I will be very grateful :)

**Comment by l-lin** [comment]
There are 4 types of renderer:
* Default renderer: used to render table with data directly inside the DOM
 * The [reloadData](https://github.com/l-lin/angular-datatables/blob/dev/dist/angular-datatables.js#L822) is indeed the one you mention, since you cannot reload data that are already in the DOM
* Angular renderer: if you want to use angular directives
 * Check the [reloadData](https://github.com/l-lin/angular-datatables/blob/dev/dist/angular-datatables.js#L905) implementation
* Promise renderer: if you want to use a promise to fetch the data
 * Check the [reloadData](https://github.com/l-lin/angular-datatables/blob/dev/dist/angular-datatables.js#L980) implementation
* Ajax renderer: if you want to use an URL to fetch the data
 * This is the [reloadData](https://github.com/l-lin/angular-datatables/blob/dev/dist/angular-datatables.js#L1128) implementation you want to check

**Comment by victorhazbun** [comment]
@l-lin there is no such reloadData function. Please provide documentation.

**Comment by l-lin** [comment]
See http://l-lin.github.io/angular-datatables/archives/#/dataReloadWithAjax and http://l-lin.github.io/angular-datatables/archives/#/dataReloadWithPromise
