### ISSUE TITLE
Datatable Disappearing After Adding or Removing 2 Entries

### ISSUE THREAD

**Issue by matthewrhoden1** [l-lin/angular-datatables#852]
## What are the versions you are using?
- jquery version: 1.12.4
- datatables version: 1.10.12
- angular-datatables version: 0.5.4
## What's the problem?

Adding or removing rows after a column sort has been changed will cause the table to disappear. In the plunker, I listed both points and it's easy to reproduce.
## Can you share your code?

https://embed.plnkr.co/dIbP4LUszpGQiCyQQUhG/

**Comment by l-lin** [comment]
The flashing issue is because the table must be rerendered. Indeed, with the angular renderer, the table must be destroyed, and then, `DataTables()` must be recalled to render the table. I don't have any other solution for this part, unfortunately...

The issue about the table disappearance is kinda weird. I tested some options, and it seems the problem occurred only when there are some data (with only 3 rows, I don't reproduce the issue) and when there are a default order. By removing the `.withOption("order", [[1, "asc"]])`, there are no issue.

I'll investigate a bit...

**Comment by matthewrhoden1** [comment]
Ok, thanks for your fast reply l-lin!

**Comment by matthewrhoden1** [comment]
In the event someone is in my exact same position, I made a quick implementation to get around these issues. If @l-lin would like to extend this I'm up for it. At the moment this is a work around for me. I hate stumbling across duplicate scenarios on the internet 2+ years later with no updates or solutions posted... Anyway, here's what I did:

http://embed.plnkr.co/guzjbTKdKE9QKVfLGNKb/

A lot of the styling is missing and filtering doesn't stack, but sorting, filtering, default ordering and dynamic updates to the collection are all possible.

Keep in mind I'm only a month old on Angular and a lot of this might be going against conventions.
