### ISSUE TITLE
Two ajax calls when changing both dtColumns and dtOptions

### ISSUE THREAD

**Issue by McGiogen** [l-lin/angular-datatables#879]
## What versions you are using?
- jquery version: 3.1.1
- datatables version: 1.10.12
- angular-datatables version: 0.5.5
## What's the problem?

I have a server-side processed table which use ajax to obtain paginated data. The user can choose between three different types of data to load in the table and each of them has its own ajax and columns. I also use yadcf plugin, which is a filter configurable per column via dtOptions.

**In short**: any time the user change the data type I have to change both dtOptions and dtColumns.

**The problem is**: any time the user change the data type, datatables fires two ajax calls with the same data.
## The code

```
/* Sample javascript */
vm.changeConfigByType = function (type) {
    switch (type) {
        case 'type1':
            vm.dtOptions = this.DTOptionsBuilder.newOptions()
                .withOption('ajax', 'myAjaxCall')
                .withOption('processing', true)
                .withOption('serverSide', true)
                .withYadcf([ ... my filters ... ]);

            vm.dtColumns = [
                this.DTColumnBuilder.newColumn('id').withTitle('Id'),
                this.DTColumnBuilder.newColumn('subname').withTitle('Subname'),
                this.DTColumnBuilder.newColumn('name').withTitle('Name'),
            ];
            break;
        case 'type2':
            vm.dtOptions = this.DTOptionsBuilder.newOptions()
                .withOption('ajax', 'myAlternativeAjaxCall')
                .withOption('processing', true)
                .withOption('serverSide', true)
                .withYadcf([ ... my alternative filters ... ]);

            vm.dtColumns = [
                this.DTColumnBuilder.newColumn('id').withTitle('Id'),
                this.DTColumnBuilder.newColumn('value2').withTitle('Another value'),
                this.DTColumnBuilder.newColumn('value3').withTitle('Still another value'),
            ];
    }
}

/* Sample html */
<table datatable
    dt-options="vm.dtOptions"
    dt-columns="vm.dtColumns"
    class="table table-hover">
</table>
```
## How to solve

I think the problem lies [here](https://github.com/l-lin/angular-datatables/blob/v0.5.5/src/angular-datatables.directive.js#L35).

```
angular.forEach(['dtColumns', 'dtColumnDefs', 'dtOptions'], function(tableDefField) {
    $scope[watchFunction].call($scope, tableDefField, handleChanges, true);
});
```

Angular-datatables sets three watchers (on dtColumn, dtColumnDefs and dtOptions) with the same listener function (`handleChanges`) which reload the table that fires the ajax call.

Changing two of those attributes at the same time causes javascript to execute two times the listener function which fire two ajax requests.

**The solution**(?): replace those three watchers with only one [$watchGroup](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watchGroup).

**Comment by l-lin** [comment]
Indeed. As a workaround, you can put everything in DTOptions:
```js
vm.dtOptions = this.DTOptionsBuilder.newOptions()
                .withOption('ajax', 'myAjaxCall')
                .withOption('processing', true)
                .withOption('serverSide', true)
                .withOption('columns', [... your columns here instead of dtColumns ...])
                .withYadcf([ ... my filters ... ]);
```

**Comment by McGiogen** [comment]
Thanks for the advice!

**Comment by sangeetashah** [comment]
jquery version: v1.11.3 
datatables version: 1.10.13
angular-datatables version: v0.5.4

We have a follow up question to the original question posted by McGiogen. We are using angular datatables and serverside processing. For this particular table - we define our columns but initially hide all of them. Once, the user specifies some filter criteria we fetch the data based on the filter criteria and then decide which columns should be displayed based on the result set. 

We've noticed that there are always 2 AJAX calls that are made. The draw value is 1 (draw:1) for both the ajax calls and the calls are exactly the same.

We tried using aoColumns instead of using the DTColumnBuilder but it didn't get rid of the extra AJAX call so either our scenario is slightly different or we are doing something incorrectly. Any help is appreciated!

Call 1:  Seems to be triggered by the call to: dtInstance.reloadData(callback, resetPaging = true);
Call 2: Seems to be automatically triggered by angular datatables when the visibility of the columns is toggled

**`Code snippet:`**
`
**vm.dtOptions** = DTOptionsBuilder.fromSource(php_path)
       .withDataProp('data')
       .withOption('serverSide', true)
       .withOption('processing', true)
       .withOption('bFilter', false)
       .withOption('bInfo', false)
       .withOption('ajax', {
          "url": php_path,
          "error": handleAjaxError,
          **"dataSrc": function ( json ) {**
                if(!json.data)
                   return [];
                if(json.data.length <= 0)
                   return [];
                 vm.showTable = false;
                 **changeColumnDefs**(json.data);
               },
         "data": function (d) {
                     d.sessionId = session_id;
                     d.searchFilter = TableService.getUsageSummaryFilter();
                  }
       })
       .withBootstrap()
       .withPaginationType('full')
       .withOption('order', [[0,'desc']])
       .withOption('responsive', true);

 **vm.dtColumns** = [
       DTColumnBuilder.newColumn('MONTH').withTitle('Month')
          .withOption('className', 'text-left').renderWith(renderMonth).notVisible(),
  
    ];

The changeColumnDefs function is called every time the data is successfully received from the server which is responsible for hiding/showing the column based on the result set:

 function **changeColumnDefs**(data)
  {
       var firstRow = data[0];
       if("YEAR" in firstRow)
       {
          vm.dtColumns[1].bVisible = true;
       }
       else
       {
           vm.dtColumns[1].bVisible = false;
       }
}
`

**Comment by l-lin** [comment]
Unfortunately, I can't find a way to have a dynamical column visibility when fetching data using server side processing...
If you do not user server side processing, you can first fetch the data from the server and put the content in the [data attribute](https://datatables.net/reference/option/data).

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
