### ISSUE TITLE
insertBefore may fail using the AngularWay

### ISSUE THREAD

**Issue by nicoabie** [l-lin/angular-datatables#91]
It seems that sometimes its second param (settings.nTableReinsertBefore the datatables loading message) is not yet inserted in the DOM
Throwing "Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."

I couldn't found the cause of it to happen, but a "fix" I've found was

``` javascript
try {
    orig.insertBefore(table, settings.nTableReinsertBefore);    
}catch(ex){
    console.log(ex);
    orig.appendChild(table);
}
```

To force its replication, render a table using the angularway, remove from dom the loading message and render it again.

**Comment by noteStylet** [comment]
I have the same Problem.
The problem is when you have multiple tabs that  contains angular-datatables.
And when a new data arrives, the error is throwed as tabs have.

I am using bootstrap tabs, 
and if I have a 5 tabs, wahen new data arrives, the error is thrown 5 times.

So I understand that he will modify the DOM, but the DOM dosn't exist because we can show 1 tab a time.
(Sorry for my englsih)

**Comment by l-lin** [comment]
Using [Angular Bootstrap](http://angular-ui.github.io/bootstrap/#/tabs), I do not have this issue.
I don't know about using only Bootstrap though...

**Comment by zafra6** [comment]
Hey guys, maybe we can use an <b>if-else validation</b> instead of a <b>try-catch validation</b>. I'm working with multiple AngularWay datatables, so sometimes in console appears this exception (DOMException), that made think that something is wrong when actually is not. Besides it'll improve the performance
<pre>
<code>
if(orig.contains(settings.nTableReinsertBefore)){
     orig.insertBefore(table, settings.nTableReinsertBefore);
} else {
     orig.appendChild(table);
}
</code>
</pre>

**Comment by SeoRoman** [comment]
Also, I am using angular bootstrap, using <tabset> and <tab> and also having the same issue as mentioned above.

issue...

<table datatable="ng"> // primary,

click on edit (opened modal, with angular tabs) one of the tabs has another datatable = "ng" and the Node error pops up...

Using Zafra6's solution has resolved the issue :)

**Comment by geeklisted** [comment]
Interestingly, I am not using tabs (bootstrap or otherwise) but I am using static dataTables and am encountering this issue.  I modified angular-datatables.js with zafra6's suggestion and the exception is actually being thrown to the console.

I wonder if just removing the log.warn(ex) from the original try-catch is a better solution for now.
