### ISSUE TITLE
Setting title on Data Reload

### ISSUE THREAD

**Issue by spacebiscuit** [l-lin/angular-datatables#963]
Using:

angular version: 1.6.0
jquery version: 1.2.1
datatables version: 1.10.13
angular-datatables version: v0.5.7

I am using data reload with ajax promise. I would like to change the title of the page when the button is reloaded.

https://plnkr.co/edit/MDtfrbS1P10RwjMOQv3R?p=preview

I would imagine that this should be handled by the changeData function but it looks to be part of the core API. What is the role of the call back in this case (taken from the exmaple) as it doesn't seem to do anything.

Thanks in advance.

SB.

**Comment by l-lin** [comment]
To change the title when reloading the data, you can do it via the callback function.
- Using ajax: https://plnkr.co/edit/RQzSdWU5c7IUGWgdYcQd?p=preview
  - We need to use `$timeout` because Angular has its own digest cycle, so we use `$timeout` to trigger the digest loop, thus affecting the value of the title
- Using promise: https://plnkr.co/edit/29ph0tjjCk0cQ4RJtF6s?p=preview
  - By using the `$q` from Angular, no need to "hack" with `$timeout` as it's in the same digest cycle

**Comment by spacebiscuit** [comment]
Strange - exactly the same code on my server but the callback function is never called! The only difference is that I am getting the data from an external source not a local file.

**Comment by spacebiscuit** [comment]
Thanks for the update but I am using changeData not reloadData on the click. It seems that callback isn't called on changeData though?

Perhaps I could just call another function on the click and set the title accordingly?

**Comment by spacebiscuit** [comment]
I got it working with a different approach, seems far more straightforward and easier to follow:

https://plnkr.co/edit/b3JcuuKOXeRvtt7r3l80?p=preview
